# Dataset

In [2]:
import pandas as pd

In [3]:
from IPython.display import display
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.expand_frame_repr', True)

In [4]:
NER = pd.read_excel("NER.xlsx")

In [5]:
NER.shape

(129249, 9)

In [6]:
df = NER[["RIC", "NER_combined"]]

In [7]:
df.shape

(129249, 2)

In [8]:
df.head()

   RIC                                      NER_combined
0  COR              [('CIF', 'ORG'), ('CIF FOB', 'ORG')]
1  COR  [('Philippine', 'NORP'), ('South Korea', 'GPE')]
2  COR                             [('Thailand', 'GPE')]
3  COR          [('Northeast', 'ORG'), ('China', 'GPE')]
4  COR                                                []

In [9]:
# Combine all normalized entities per RIC
grouped_df = df.groupby("RIC")["NER_combined"].sum().reset_index()

In [10]:
grouped_df.shape

(2216, 2)

In [11]:
grouped_df.head()

         RIC  \
0  000150.KS
1  002230.SZ
2  002281.SZ
3  002405.SZ
4  002432.SZ

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              NER_combined
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      [('Second Quarter', 'DATE')][('11 cent', 'MONEY'), ('CERV Cervus Equipment', 'ORG')][('Cervus Equipment Corporation Cervus', 'ORG'), ('Second Quarter', 'DATE'), ('Cervus Equipment Corporation', 'ORG'), ('Cervus', 'ORG')][('Press Release Cervus', 'ORG'), ('Second Quarter', 'DATE'), ('Cervus', 'ORG')][('Second Quarter', 'DATE'), ('Cervus', 'ORG')][('Asia Pacific Corporate', 'ORG'), ('13', 'CARDINAL'), ('Asia Pacific Corporate Calendar', 'EVENT'), ('Month Ahead', 'DATE'), ('13', 'DATE')][('Doosan', 'PRODUCT'), ('Korean', 'NORP')][('06 09', 'CARDINAL'), ('NH Investment & Securities Previously Woori Research', 'ORG'), ('Second Half', 'DATE'), ('06 09', 'DATE')][('MSCI ESG Research', 'ORG'), ('Doosan Corporation', 'ORG')][('Korea', 'GPE'), ('SK', 'ORG')][('Cervus Equipment Corporation Cervus Equipment Peterbilt', 'ORG'), ('Open New TRP Parts Location', 'ORG'), ('Cervus Equipment Corporation', 'ORG'), ('Cervus Equipment Peterbilt', 'ORG'), ('Prince Albert', 'GPE'), ('Saskatchewan', 'GPE')][('200', 'CARDINAL'), ('6', 'CARDINAL')][('REG Ceres Power Holdings Notice of Capital Markets Teach', 'ORG'), ('REG Ceres Power Holdings', 'ORG')][][('BitPath CAST.ERA', 'ORG'), ('ONE', 'CARDINAL'), ('ONE Media', 'ORG')][('BitPath CAST.ERA', 'ORG'), ('ONE', 'CARDINAL'), ('ONE Media', 'ORG'), ('NextGen Broadcast Standard', 'PRODUCT')][('Doosan Corp MarketLine', 'ORG'), ('Doosan Corp', 'ORG')][('Daegu Mao Elementary School Expression', 'PERSON'), ('Daegu Mao', 'ORG')][('Eastern Environmental Improvement Electric Sector Design Service', 'ORG'), ('Daegu Doosan Elementary School', 'FAC'), ('nautmark Eastern Environmental Improvement', 'ORG')][("the Rolls Royce Group's", 'ORG'), ('Competition Authority of the French Republic', 'ORG'), ('Autorité', 'ORG'), ('Framatome', 'ORG'), ('EDF', 'ORG')][('Industrial Air Compressor Market', 'ORG'), ('17.8', 'MONEY'), ('Global Market Insights Inc.', 'ORG'), ('$17.8 Bn', 'MONEY')][('Doosan Bobcat', 'PERSON'), ('Cogniac', 'ORG')][('Sustain Asia Daily', 'ORG'), ('Japan', 'GPE'), ('26', 'CARDINAL'), ('CLSA', 'ORG'), ('Japan week', 'DATE'), ('26 May CLSA', 'DATE')][('Machines From The Manufacturer Doosan', 'WORK_OF_ART'), ('Doosan', 'ORG')][('Korea Morning Notes', 'ORG'), ('26', 'CARDINAL'), ('CLSA', 'ORG'), ('Korea', 'GPE'), ('26 May', 'DATE')][('Korea', 'GPE'), ('CLSA', 'ORG')][('BBB0', 'PERSON'), ('Doosan', 'ORG')][('Seoul', 'GPE'), ('Korean', 'NORP')][('Warranty Maintenance Services Doosan Dx200a', 'ORG'), ('Doosan', 'PRODUCT'), ('Dx200a', 'PRODUCT'), ('Excavator', 'PRODUCT'), ('dhkcebdxcl0001807', 'PRODUCT')]
1  [('Iflytek Co Ltd', 'ORG'), ('Overnight Returns Marktfeld', 'PERSON'), ('Intraday', 'TIME'), ('Overnight', 'TIME'), ('Marktfeld', 'PERSON')][('China', 'GPE'), ('China Software', 'ORG'), ('Goldman Sachs', 'ORG')][('Iflytek', 'ORG'), ('China Knowledge Online Pte. Ltd.', 'ORG'), ('1', 'CARDINAL'), ('Apr', 'DATE')][('China', 'GPE'), ('Goldman Sachs', 'ORG')][('China', 'GPE'), ('Zhuiyi AI /', 'PERSON'), ('NLP', 'ORG'), ('75%', 'PERCENT'), ('17', 'CARDINAL'), ('China Software', 'ORG'), ('Goldman Sachs', 'ORG')][('APAC Quantitative & Systematic Strategy Northbound', 'ORG'), ('Credit Suisse', 'ORG')][('HK Bourse Results Announcement', 'ORG'), ('33', 'CARDINAL'), ('HK Bourse', 'ORG'), ('Great Wall Motor 33', 'ORG')][('HK Bourse Announcement', 'ORG'), ('Chinasoft International', 'FAC'), ('9', 'CARDINAL'), ('Chinasoft International 9', 'ORG')][('iFLYTEK Co. Ltd.', 'ORG'), ('MarketLine', 'PERSON')][('NIKKEI Asia Pacific Corporate', 'ORG'), ('19 2', 'CARDINAL'), ('NIKKEI', 'ORG')][('NIKKEI Asia Pacific Corporate', 'ORG'), ('18 2', 'CARDINAL'), ('NIKKEI', 'ORG')][('HK Bourse Announcement', 'ORG'), ('China Merchants Direct', 'ORG'), ('6', 'CARDINAL')][('Iflytek 002230', 'DATE'), ('Mar', 'PERSON'), ('China Knowledge Online Pte. Ltd.', 'ORG'), ('Iflytek', 'ORG'), ('002230', 'PRODUCT'), ('Mar', 'ORG')][('New Decade', 'EVENT'), ('AWE2021', 'EVENT')][('Press Release Kingdee International', 'ORG'), ('Kingdee International', 'ORG'), ('Annual', 'DATE')][('Kingdee International', 'ORG'), ('Annual', 'DATE')][('iFlytek', 'ORG'), ('Tindall', 'ORG')][('Iflytek Co Ltd Deliver Long Term Returns Sadif Analytics', 'ORG'), ('Iflytek Co Ltd', 'ORG'), ('Sadif Analytics', 'ORG')][('NZ', 'GPE'), ('Australia', 'GPE'), ('China', 'GPE'), ('NZ Australia', 'GPE')][('AWE', 'ORG'), ('Haier Smart Home Brings', 'PERSON'), ('Smart Home Solution', 'ORG'), ('Haier', 'ORG')][('Haier Smart Home Brings', 'PERSON'), ('Smart Home Solution', 'ORG'), ('Haier', 'ORG')][('Haier Smart Home Brings', 'PERSON'), ('Smart Home Solution', 'ORG'), ('Haier', 'ORG')][('Software & Services Results Preview Software & services', 'ORG'), ('19', 'CARDINAL'), ('China International Capital Corporation', 'ORG'), ('COVID 19', 'EVENT'), ('China International Capital Corporation Hong Kong Limited', 'ORG')][('Software & Services Results Preview Software & services', 'ORG'), ('19', 'CARDINAL'), ('China International Capital Corporation', 'ORG'), ('COVID 19', 'EVENT'), ('China International Capital Corporation Hong Kong Limited', 'ORG')][('China Software LinkingMed', 'ORG'), ('AI Medical', 'ORG'), ('Goldman Sachs', 'ORG')][('Asia Pacific Corporate', 'ORG'), ('26', 'CARDINAL'), ('Asia Pacific Corporate Calendar', 'EVENT'), ('Month Ahead', 'DATE'), ('26', 'DATE')][('Asia Pacific Corporate', 'ORG'), ('25', 'CARDINAL'), ('Asia Pacific Corporate Calendar', 'EVENT'), ('Month Ahead', 'DATE'), ('25', 'DATE')][('Greater China Technology Hardware Incorporating', 'ORG'), ('Greater China Technology Hardware', 'ORG'), ('Morgan Stanley', 'ORG')][('Uyghur', 'ORG'), ('Consulate', 'ORG')][('MSCI ESG Research', 'ORG'), ('IFLYTEK CO. LTD', 'ORG')][('China', 'GPE')][('China', 'GPE'), ('Govt', 'ORG')][('Beijing', 'GPE'), ('136', 'CARDINAL'), ('Tencent', 'ORG'), ('iFlyTek', 'ORG')][('MSCI ESG Research', 'ORG'), ('IFLYTEK CO. LTD', 'ORG'), ('MSCI ESG', 'ORG')][('Beijing', 'GPE'), ('over 100', 'CARDINAL'), ('iFlyTek Tencent', 'ORG')][('Iflytek', 'ORG'), ('Q3', 'DATE'), ('China Knowledge Online Pte. Ltd.', 'ORG')][('Iflytek', 'ORG'), ('Foreign Investors Rating China Knowledge Online Pte. Ltd.', 'ORG'), ('Foreign Investors Rating', 'ORG'), ('China Knowledge Online Pte. Ltd.', 'ORG')][('002230', 'DATE'), ('China Knowledge Online Pte. Ltd.', 'EVENT'), ('Iflytek', 'ORG'), ('China Knowledge Online Pte. Ltd.', 'ORG')][('Iflytek', 'ORG'), ('Q4', 'ORG'), ('China Knowledge Online Pte. Ltd.', 'ORG'), ('Q4', 'DATE')][('Iflytek', 'ORG'), ('2', 'CARDINAL'), ('Pte. Ltd.', 'ORG')][('Iflytek', 'ORG'), ('one', 'CARDINAL'), ('China Knowledge Online Pte. Ltd.', 'ORG'), ('2', 'CARDINAL')][('Iflytek', 'ORG'), ('one', 'CARDINAL'), ('China Knowledge Online Pte. Ltd.', 'ORG'), ('3', 'CARDINAL')][('Iflytek', 'ORG'), ('one', 'CARDINAL'), ('China Knowledge Online Pte. Ltd.', 'ORG'), ('3', 'CARDINAL')][('MarketGrader Research Report', 'ORG'), ('iflytek Co. Ltd.', 'ORG')][('Iflytek 002230', 'DATE'), ('one', 'CARDINAL'), ('China Knowledge Online Pte. Ltd.', 'ORG'), ('Iflytek', 'ORG'), ('002230', 'PRODUCT'), ('Q1', 'DATE')]
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [('Accelink Technologies', 'ORG'), ('China Knowledge Online Pte.', 'ORG'), ('2', 'CARDINAL'), ('Oct', 'DATE'), ('China Knowledge Online Pte. Ltd.', 'ORG')][('Accelink Technologies 002281.SZ Data Update', 'ORG'), ('3Q21 Goldman Sachs', 'ORG'), ('Accelink Technologies', 'ORG'), ('3Q21', 'DATE'), ('Goldman Sachs', 'ORG')][('First Read Accelink Technologies "Transmission', 'ORG'), ('biz grew', 'PERSON'), ('UBS Equities', 'ORG'), ('First Read Accelink Technologies', 'ORG')][('Accelink Technologies', 'ORG'), ('1', 'CARDINAL'), ('Citi', 'GPE'), ('Citi', 'ORG')][('Asian Daily China', 'ORG'), ('3Q21', 'ORG'), ('5', 'CARDINAL'), ('OUTPERFORM Credit Suisse', 'ORG'), ('Asian Daily', 'ORG'), ('China Accelink', 'ORG'), ('3Q21', 'DATE'), ('Credit Suisse', 'ORG')][('Asia Pacific Corporate', 'ORG'), ('3', 'CARDINAL'), ('Asia Pacific', 'LOC')][('Asia Pacific Corporate', 'ORG'), ('5', 'CARDINAL'), ('Asia Pacific', 'LOC')][('Asia Pacific Corporate', 'ORG'), ('8', 'CARDINAL')][('Accelink Technologies', 'ORG'), ('002281', 'DATE'), ('one', 'CARDINAL'), ('China Knowledge Online Pte. Ltd.', 'ORG'), ('Accelink Technologies 002281', 'ORG'), ('Oct', 'DATE')][('Asian Daily China Accelink Self', 'ORG'), ('OUTPERFORM Credit Suisse', 'ORG'), ('Asian Daily', 'ORG'), ('China Accelink', 'ORG'), ('Credit Suisse', 'ORG')][('China Communication Infrastructure Sector Accelerating', 'ORG'), ('2H21', 'CARDINAL'), ('1H22', 'CARDINAL'), ('Credit Suisse', 'ORG'), ('China', 'GPE'), ('2H21 1H22', 'DATE')]

In [12]:
grouped_df[grouped_df['RIC'] == 'HYFM.OQ']

,RIC,NER_combined
980,HYFM.OQ,"[('Hydrofarm Holdings Group Inc', 'ORG'), ('HYFM', 'ORG'), ('Q4', 'DATE')][('Q4 Hydrofarm Holdings Group Inc Earnings Call', 'ORG'), ('Q4', 'DATE'), ('Hydrofarm Holdings Group Inc', 'ORG')][('Hydrofarm Holdings Group Inc.', 'ORG'), ('HYFM', 'ORG'), ('Q4', 'DATE')][('US Penny Stocks', 'ORG'), ('January', 'DATE'), ('US', 'GPE')][('Zacks Industry Outlook Highlights West Fraser', 'ORG'), ('CalMaine Foods Andersons', 'ORG'), ('Hydrofarm', 'PERSON'), ('Zacks', 'ORG'), ('West Fraser Timber', 'ORG'), ('CalMaine Foods', 'ORG'), ('Hydrofarm', 'ORG')][('4 Agriculture Products Stocks', 'ORG'), ('Watch Despite Industry Concerns', 'ORG'), ('4', 'CARDINAL')][('Hydrofarm Holdings Group Inc.', 'ORG'), ('Invest', 'ORG'), ('HYFM', 'ORG')][('Hydrofarm Holdings Group', 'ORG')][('3 US Penny', 'MONEY'), ('3', 'CARDINAL'), ('US', 'GPE'), ('30', 'MONEY')][('Hydrofarm', 'ORG'), ('FY24', 'DATE')][('Hydrofarm Holdings Group Inc', 'ORG'), ('HYFM', 'ORG'), ('Q4', 'DATE')][('Q4 Hydrofarm Holdings Group Inc Earnings Call', 'ORG'), ('Q4', 'DATE'), ('Hydrofarm Holdings Group Inc', 'ORG')][('Hydrofarm Holdings Group Inc.', 'ORG'), ('HYFM', 'ORG'), ('Q4', 'DATE')][('US Penny Stocks', 'ORG'), ('January', 'DATE'), ('US', 'GPE')][('Zacks Industry Outlook Highlights West Fraser', 'ORG'), ('CalMaine Foods Andersons', 'ORG'), ('Hydrofarm', 'PERSON'), ('Zacks', 'ORG'), ('West Fraser Timber', 'ORG'), ('CalMaine Foods', 'ORG'), ('Hydrofarm', 'ORG')][('4 Agriculture Products Stocks', 'ORG'), ('Watch Despite Industry Concerns', 'ORG'), ('4', 'CARDINAL')][('Hydrofarm Holdings Group Inc.', 'ORG'), ('Invest', 'ORG'), ('HYFM', 'ORG')][('Hydrofarm Holdings Group', 'ORG')][('3 US Penny', 'MONEY'), ('3', 'CARDINAL'), ('US', 'GPE'), ('30', 'MONEY')][('Hydrofarm', 'ORG'), ('FY24', 'DATE')]"

# Word2vec

In [13]:
!pip install gensim

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gensim in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in ./.local/lib/python3.12/site-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from gensim) (5.2.1)

In [14]:
import re
import ast

def fix_broken_ner(text):
    if not isinstance(text, str):
        return text
    text_fixed = re.sub(r'\]\s*\[', ',', text)     # Fix broken small list joins
    text_fixed = re.sub(r',\s*,+', ',', text_fixed) # Fix double commas
    text_fixed = re.sub(r'\[\s*,\s*', '[', text_fixed)  # Fix opening bracket followed by comma
    return ast.literal_eval(text_fixed)

# Apply to fix NER_combined
grouped_df['NER_combined'] = grouped_df['NER_combined'].apply(fix_broken_ner)

In [15]:
grouped_df.head()

,RIC,NER_combined
0,000150.KS,"[(Second Quarter, DATE), (11 cent, MONEY), (CERV Cervus Equipment, ORG), (Cervus Equipment Corporation Cervus, ORG), (Second Quarter, DATE), (Cervus Equipment Corporation, ORG), (Cervus, ORG), (Press Release Cervus, ORG), (Second Quarter, DATE), (Cervus, ORG), (Second Quarter, DATE), (Cervus, ORG), (Asia Pacific Corporate, ORG), (13, CARDINAL), (Asia Pacific Corporate Calendar, EVENT), (Month Ahead, DATE), (13, DATE), (Doosan, PRODUCT), (Korean, NORP), (06 09, CARDINAL), (NH Investment & Securities Previously Woori Research, ORG), (Second Half, DATE), (06 09, DATE), (MSCI ESG Research, ORG), (Doosan Corporation, ORG), (Korea, GPE), (SK, ORG), (Cervus Equipment Corporation Cervus Equipment Peterbilt, ORG), (Open New TRP Parts Location, ORG), (Cervus Equipment Corporation, ORG), (Cervus Equipment Peterbilt, ORG), (Prince Albert, GPE), (Saskatchewan, GPE), (200, CARDINAL), (6, CARDINAL), (REG Ceres Power Holdings Notice of Capital Markets Teach, ORG), (REG Ceres Power Holdings, ORG), (BitPath CAST.ERA, ORG), (ONE, CARDINAL), (ONE Media, ORG), (BitPath CAST.ERA, ORG), (ONE, CARDINAL), (ONE Media, ORG), (NextGen Broadcast Standard, PRODUCT), (Doosan Corp MarketLine, ORG), (Doosan Corp, ORG), (Daegu Mao Elementary School Expression, PERSON), (Daegu Mao, ORG), (Eastern Environmental Improvement Electric Sector Design Service, ORG), (Daegu Doosan Elementary School, FAC), (nautmark Eastern Environmental Improvement, ORG), (the Rolls Royce Group's, ORG), (Competition Authority of the French Republic, ORG), (Autorité, ORG), (Framatome, ORG), (EDF, ORG), (Industrial Air Compressor Market, ORG), (17.8, MONEY), (Global Market Insights Inc., ORG), ($17.8 Bn, MONEY), (Doosan Bobcat, PERSON), (Cogniac, ORG), (Sustain Asia Daily, ORG), (Japan, GPE), (26, CARDINAL), (CLSA, ORG), (Japan week, DATE), (26 May CLSA, DATE), (Machines From The Manufacturer Doosan, WORK_OF_ART), (Doosan, ORG), (Korea Morning Notes, ORG), (26, CARDINAL), (CLSA, ORG), (Korea, GPE), (26 May, DATE), (Korea, GPE), (CLSA, ORG), (BBB0, PERSON), (Doosan, ORG), (Seoul, GPE), (Korean, NORP), (Warranty Maintenance Services Doosan Dx200a, ORG), (Doosan, PRODUCT), (Dx200a, PRODUCT), (Excavator, PRODUCT), (dhkcebdxcl0001807, PRODUCT)]"
1,002230.SZ,"[(Iflytek Co Ltd, ORG), (Overnight Returns Marktfeld, PERSON), (Intraday, TIME), (Overnight, TIME), (Marktfeld, PERSON), (China, GPE), (China Software, ORG), (Goldman Sachs, ORG), (Iflytek, ORG), (China Knowledge Online Pte. Ltd., ORG), (1, CARDINAL), (Apr, DATE), (China, GPE), (Goldman Sachs, ORG), (China, GPE), (Zhuiyi AI /, PERSON), (NLP, ORG), (75%, PERCENT), (17, CARDINAL), (China Software, ORG), (Goldman Sachs, ORG), (APAC Quantitative & Systematic Strategy Northbound, ORG), (Credit Suisse, ORG), (HK Bourse Results Announcement, ORG), (33, CARDINAL), (HK Bourse, ORG), (Great Wall Motor 33, ORG), (HK Bourse Announcement, ORG), (Chinasoft International, FAC), (9, CARDINAL), (Chinasoft International 9, ORG), (iFLYTEK Co. Ltd., ORG), (MarketLine, PERSON), (NIKKEI Asia Pacific Corporate, ORG), (19 2, CARDINAL), (NIKKEI, ORG), (NIKKEI Asia Pacific Corporate, ORG), (18 2, CARDINAL), (NIKKEI, ORG), (HK Bourse Announcement, ORG), (China Merchants Direct, ORG), (6, CARDINAL), (Iflytek 002230, DATE), (Mar, PERSON), (China Knowledge Online Pte. Ltd., ORG), (Iflytek, ORG), (002230, PRODUCT), (Mar, ORG), (New Decade, EVENT), (AWE2021, EVENT), (Press Release Kingdee International, ORG), (Kingdee International, ORG), (Annual, DATE), (Kingdee International, ORG), (Annual, DATE), (iFlytek, ORG), (Tindall, ORG), (Iflytek Co Ltd Deliver Long Term Returns Sadif Analytics, ORG), (Iflytek Co Ltd, ORG), (Sadif Analytics, ORG), (NZ, GPE), (Australia, GPE), (China, GPE), (NZ Australia, GPE), (AWE, ORG), (Haier Smart Home Brings, PERSON), (Smart Home Solution, ORG), (Haier, ORG), (Haier Smart Home Brings, PERSON), (Smart Home Solution, ORG), (Haier, ORG), (Haier Smart Home Brings, PERSON), (Smart Home Solution, ORG), (Haier, ORG), (Software & Services Results Preview Software & services, ORG), (19, CARDINAL), (China International Capital Corporation, ORG), (COVID 19, EVENT), (China International Capital Corporation Hong Kong Limited, ORG), (Software & Services Results Preview Software & services, ORG), (19, CARDINAL), (China International Capital Corporation, ORG), (COVID 19, EVENT), (China International Capital Corporation Hong Kong Limited, ORG), (China Software LinkingMed, ORG), (AI Medical, ORG), (Goldman Sachs, ORG), (Asia Pacific Corporate, ORG), (26, CARDINAL), (Asia Pacific Corporate Calendar, EVENT), (Month Ahead, DATE), (26, DATE), (Asia Pacific Corporate, ORG), (25, CARDINAL), (Asia Pacific Corporate Calendar, EVENT), (Month Ahead, DATE), (25, DATE), (Greater China Technology Hardware Incorporating, ORG), (Greater China Technology Hardware, ORG), (Morgan Stanley, ORG), ...]"
2,002281.SZ,"[(Accelink Technologies, ORG), (China Knowledge Online Pte., ORG), (2, CARDINAL), (Oct, DATE), (China Knowledge Online Pte. Ltd., ORG), (Accelink Technologies 002281.SZ Data Update, ORG), (3Q21 Goldman Sachs, ORG), (Accelink Technologies, ORG), (3Q21, DATE), (Goldman Sachs, ORG), (First Read Accelink Technologies ""Transmission, ORG), (biz grew, PERSON), (UBS Equities, ORG), (First Read Accelink Technologies, ORG), (Accelink Technologies, ORG), (1, CARDINAL), (Citi, GPE), (Citi, ORG), (Asian Daily China, ORG), (3Q21, ORG), (5, CARDINAL), (OUTPERFORM Credit Suisse, ORG), (Asian Daily, ORG), (China Accelink, ORG), (3Q21, DATE), (Credit Suisse, ORG), (Asia Pacific Corporate, ORG), (3, CARDINAL), (Asia Pacific, LOC), (Asia Pacific Corporate, ORG), (5, CARDINAL), (Asia Pacific, LOC), (Asia Pacific Corporate, ORG), (8, CARDINAL), (Accelink Technologies, ORG), (002281, DATE), (one, CARDINAL), (China Knowledge Online Pte. Ltd., ORG), (Accelink Technologies 002281, ORG), (Oct, DATE), (Asian Daily China Accelink Self, ORG), (OUTPERFORM Credit Suisse, ORG), (Asian Daily, ORG), (China Accelink, ORG), (Credit Suisse, ORG), (China Communication Infrastructure Sector Accelerating, ORG), (2H21, CARDINAL), (1H22, CARDINAL), (Credit Suisse, ORG), (China, GPE), (2H21 1H22, DATE)]"
3,002405.SZ,"[(ADAS Company MINIEYE Closes C Round of Financing, ORG), (270 Million RMB, MONEY), (ADAS, ORG), (MINIEYE, ORG), (World ADAS & AV Technologies and Components Market Report Focus on Camera Radar & Lidar, ORG), (Mapping & Localization and Robotaxis, ORG), (Montage Rare, PERSON), (Credit Suisse, ORG), (NavInfo Co. Ltd. Mergers & Acquisitions M&A Partnerships & Alliances and, ORG), (NavInfo Co. Ltd., ORG), (Mergers & Acquisitions, ORG), (China, GPE), (September, DATE), (Daiwa Capital Markets Hong Kong Ltd., ORG), (Technavio, ORG)]"
4,002432.SZ,"[(Blood Glucose Monitoring Devices Market Size, ORG), (Arizton, ORG), (USD 37 Billion, MONEY), (Arizton, GPE), (MarketGrader Research Report, ORG), (Andon Health Co. Ltd., ORG)]"

In [16]:
corpus = []
for ner_list in grouped_df['NER_combined']:
    tokens = [entity.replace(' ', '_') for entity, label in ner_list]
    tokens = list(dict.fromkeys(tokens))  # Deduplicate inside one RIC
    corpus.append(tokens)

In [17]:
from gensim.models import Word2Vec

w2v_model = Word2Vec(
    sentences=corpus,
    vector_size=100,
    window=2,
    min_count=1,
    workers=4,
    sg=1,
    sample=1e-3
)

In [18]:
import numpy as np

def get_ric_vector(ner_list):
    tokens = [entity.replace(' ', '_') for entity, label in ner_list]
    tokens = list(dict.fromkeys(tokens))  # deduplicate
    vectors = []
    for token in tokens:
        if token in w2v_model.wv:
            vectors.append(w2v_model.wv[token])
    if vectors:
        return np.mean(vectors, axis=0)  # Average embedding
    else:
        return np.zeros(w2v_model.vector_size)

grouped_df['RIC_Vector'] = grouped_df['NER_combined'].apply(get_ric_vector)

In [19]:
grouped_df.head()

,RIC,NER_combined,RIC_Vector
0,000150.KS,"[(Second Quarter, DATE), (11 cent, MONEY), (CERV Cervus Equipment, ORG), (Cervus Equipment Corporation Cervus, ORG), (Second Quarter, DATE), (Cervus Equipment Corporation, ORG), (Cervus, ORG), (Press Release Cervus, ORG), (Second Quarter, DATE), (Cervus, ORG), (Second Quarter, DATE), (Cervus, ORG), (Asia Pacific Corporate, ORG), (13, CARDINAL), (Asia Pacific Corporate Calendar, EVENT), (Month Ahead, DATE), (13, DATE), (Doosan, PRODUCT), (Korean, NORP), (06 09, CARDINAL), (NH Investment & Securities Previously Woori Research, ORG), (Second Half, DATE), (06 09, DATE), (MSCI ESG Research, ORG), (Doosan Corporation, ORG), (Korea, GPE), (SK, ORG), (Cervus Equipment Corporation Cervus Equipment Peterbilt, ORG), (Open New TRP Parts Location, ORG), (Cervus Equipment Corporation, ORG), (Cervus Equipment Peterbilt, ORG), (Prince Albert, GPE), (Saskatchewan, GPE), (200, CARDINAL), (6, CARDINAL), (REG Ceres Power Holdings Notice of Capital Markets Teach, ORG), (REG Ceres Power Holdings, ORG), (BitPath CAST.ERA, ORG), (ONE, CARDINAL), (ONE Media, ORG), (BitPath CAST.ERA, ORG), (ONE, CARDINAL), (ONE Media, ORG), (NextGen Broadcast Standard, PRODUCT), (Doosan Corp MarketLine, ORG), (Doosan Corp, ORG), (Daegu Mao Elementary School Expression, PERSON), (Daegu Mao, ORG), (Eastern Environmental Improvement Electric Sector Design Service, ORG), (Daegu Doosan Elementary School, FAC), (nautmark Eastern Environmental Improvement, ORG), (the Rolls Royce Group's, ORG), (Competition Authority of the French Republic, ORG), (Autorité, ORG), (Framatome, ORG), (EDF, ORG), (Industrial Air Compressor Market, ORG), (17.8, MONEY), (Global Market Insights Inc., ORG), ($17.8 Bn, MONEY), (Doosan Bobcat, PERSON), (Cogniac, ORG), (Sustain Asia Daily, ORG), (Japan, GPE), (26, CARDINAL), (CLSA, ORG), (Japan week, DATE), (26 May CLSA, DATE), (Machines From The Manufacturer Doosan, WORK_OF_ART), (Doosan, ORG), (Korea Morning Notes, ORG), (26, CARDINAL), (CLSA, ORG), (Korea, GPE), (26 May, DATE), (Korea, GPE), (CLSA, ORG), (BBB0, PERSON), (Doosan, ORG), (Seoul, GPE), (Korean, NORP), (Warranty Maintenance Services Doosan Dx200a, ORG), (Doosan, PRODUCT), (Dx200a, PRODUCT), (Excavator, PRODUCT), (dhkcebdxcl0001807, PRODUCT)]","[-0.002995042, -0.0015325773, -0.0036825573, 0.0028167297, -0.0008894572, -0.0025599445, -0.0015886788, 0.00661676, -0.0037440944, -0.00093713077, 0.00092404097, -0.0017074952, -0.0012354119, 8.9960085e-05, -0.0012017325, 0.0017013592, 0.0028511195, -0.003939589, 0.0006460512, -0.008583811, -0.0019023409, -0.00039076645, 0.0035725764, 0.00079848047, -0.00045158243, -0.00064549415, -0.0005411465, 0.0045708823, -0.0035633768, 0.0023697559, 0.0066629876, 0.0015193239, 0.0013327332, -0.0046284203, -0.005101461, 0.004192968, -0.0011695002, 0.0018015236, 0.0004058075, 0.0017370079, 0.006409451, -0.0036421395, -0.0052502565, -0.003090842, 0.0022379055, -0.00040561418, -0.0021341378, 0.0018248494, 0.005026039, 0.005793105, 0.0037054855, -0.00040492887, 0.0033179428, 0.0036241089, -0.00010660662, -0.0036879452, -0.00096845726, -0.0011869286, -0.0030272708, -0.0023882592, 0.0008560257, 0.0012754416, 0.0069657327, 0.0013868931, -0.0021651033, -0.0026102136, -0.00048086126, 0.00074355106, -0.0045319893, 0.00024985182, 0.0027662653, 0.0044214716, 0.001275905, -0.0022579625, 0.003112041, -0.0008231902, 0.0014096139, 0.0022464718, 0.004252465, -0.0028183125, -0.0025656857, -0.004469267, -0.003046351, 0.0020587267, -0.0016948549, -0.004306375, -0.0023795094, 0.004835454, 0.0011295825, 0.0002883321, -0.0011466233, 0.0026944615, 0.0022386487, 0.00028591976, 0.004901935, -0.0054136696, -0.0013867032, -0.0016537734, 0.0042197783, -9.7620185e-05]"
1,002230.SZ,"[(Iflytek Co Ltd, ORG), (Overnight Returns Marktfeld, PERSON), (Intraday, TIME), (Overnight, TIME), (Marktfeld, PERSON), (China, GPE), (China Software, ORG), (Goldman Sachs, ORG), (Iflytek, ORG), (China Knowledge Online Pte. Ltd., ORG), (1, CARDINAL), (Apr, DATE), (China, GPE), (Goldman Sachs, ORG), (China, GPE), (Zhuiyi AI /, PERSON), (NLP, ORG), (75%, PERCENT), (17, CARDINAL), (China Software, ORG), (Goldman Sachs, ORG), (APAC Quantitative & Systematic Strategy Northbound, ORG), (Credit Suisse, ORG), (HK Bourse Results Announcement, ORG), (33, CARDINAL), (HK Bourse, ORG), (Great Wall Motor 33, ORG), (HK Bourse Announcement, ORG), (Chinasoft International, FAC), (9, CARDINAL), (Chinasoft International 9, ORG), (iFLYTEK Co. Ltd., ORG), (MarketLine, PERSON), (NIKKEI Asia Pacific Corporate, ORG), (19 2, CARDINAL), (NIKKEI, ORG), (NIKKEI Asia Pacific Corporate, ORG), (18 2, CARDINAL), (NIKKEI, ORG), (HK Bourse Announcement, ORG), (China Merchants Direct, ORG), (6, CARDINAL), (Iflytek 002230, DATE), (Mar, PERSON), (China Knowledge Online Pte. Ltd., ORG), (Iflytek, ORG), (002230, PRODUCT), (Mar, ORG), (New Decade, EVENT), (AWE2021, EVENT), (Press Release Kingdee International, ORG), (Kingdee International, ORG), (Annual, DATE), (Kingdee International, ORG), (Annual, DATE), (iFlytek, ORG), (Tindall, ORG), (Iflytek Co Ltd Deliver Long Term Returns Sadif Analytics, ORG), (Iflytek Co Ltd, ORG), (Sadif Analytics, ORG), (NZ, GPE), (Australia, GPE), (China, GPE), (NZ Australia, GPE), (AWE, ORG), (Haier Smart Home Brings, PERSON), (Smart Home Solution, ORG), (Haier, ORG), (Haier Smart Home Brings, PERSON), (Smart Home Solution, ORG), (Haier, ORG), (Haier Smart Home Brings, PERSON), (Smart Home Solution, ORG), (Haier, ORG), (Software & Services Results Preview Software & services, ORG), (19, CARDINAL), (China International Capital Corporation, ORG), (COVID 19, EVENT), (China International Capital Corporation Hong Kong Limited, ORG), (Software & Services Results Preview Software & services, ORG), (19, CARDINAL), (China International Capital Corporation, ORG), (COVID 19, EVENT), (China International Capital Corporation Hong Kong Limited, ORG), (China Software LinkingMed, ORG), (AI Medical, ORG), (Goldman Sachs, ORG), (Asia Pacific Corporate, ORG), (26, CARDINAL), (Asia Pacific Corporate Calendar, EVENT), (Month Ahead, DATE), (26, DATE), (Asia Pacific Corporate, ORG), (25, CARDINAL), (Asia Pacific Corporate Calendar, EVENT), (Month Ahead, DATE), (25, DATE), (Greater China Technology Hardware Incorporating, ORG), (Greater China Technology Hardware, ORG), (Morgan Stanley, ORG), ...]","[-0.0013427167, 0.018509999, -0.004365821, 0.0067048655, -0.009782761, -0.0023112288, 0.01484668, 0.019901825, -0.010111331, -0.0021727078, -0.00661643, -0.010558178, -0.0059189843, 0.0057162307, 0.004080529, -0.019531276, 0.00329888, 0.0034765427, -0.008862216, -0.025719503, 0.005341016, -0.0026188921, 0.014738443, -0.010367491, -0.0065658144, 0.0024201856, -0.0116624115, -0.0046382183, -0.016002517, 0.013708689, 0.0075921803, 0.0063814106, 0.007361483, -0.0072154608, -0.0105227595, 0.008805468, 0.00012366257, 0.0130194165, -0.009078633, 0.0037745025, 0.02260092, -0.012360628, -0.018094003, -0.0014050204, 0.008915661, 0.000721566, -0.0047028093, -0.0022677793, 0.02316716, 0.008297968, -0.008128801, -0.021236505, 0.0008598487, -0.0054938337, -0.014804795, -0.0030125582, 0.012327743, -0.012111016, -0.006467494, 0.015676294, 0.0018821275, 0.003648193, 0.022975814, 0.0062351883, 0.005765857, 0.006927572, -0.003555446, 0.008368353, -0.020032082, 0.006261175, -0.012672828, 0.017093657, 0.016761083, -0.0043318155, 0.0130460365, 0.005876106, 0.0069737886, 0.011175956, 0.013961245, -0.008454586, 0.0017694804, -0.0056981063, -0.017199853, 0.0061139413, -0.0203808, -0.022385828, 0.01052955, 0.014172575, 0.0076592662, 0.0057692565, 0.0016103424, 0.013560721, -0.011975698, -0.019470388, 0.010247611, -0.0069201165, 0.018761558, -0.0117443055, 0.014970451, -0.0062152115]"
2,002281.SZ,"[(Accelink Technologies, ORG), (China Knowledge Online Pte., ORG), (2, CARDINAL), (Oct, DATE), (China Knowledge Online Pte. Ltd., ORG), (Accelink Technologies 002281.SZ Data Update, ORG), (3Q21 Goldman Sachs, ORG), (Accelink Technologies, ORG), (3Q21, DATE), (Goldman Sachs, ORG), (First Read Accelink Technologies ""Transmission, ORG), (biz grew, PERSON), (UBS Equities, ORG), (First Read Accelink Technologies, ORG), (Accelink Technologies, ORG), (1, CARDINAL), (Citi, GPE), (Citi, ORG), (Asian Daily China, ORG), (3Q21, ORG), (5, CARDINAL), (OUTPERFORM Credit Suisse, ORG), (Asian Daily, ORG), (China Accelink, ORG), (3Q21, DATE), (Credit Suisse, ORG), (Asia Pacific Corporate, ORG), (3, CARDINAL), (Asia Pacific, LOC), (Asia Pacific Corporate, ORG), (5, CARDINAL), (Asia Pacific, LOC), (Asia Pacific Corporate, ORG), (8, CARDINAL), (Accelink Technologies, ORG), (002281, DATE), (one, CARDINAL), (China Knowledge Online Pte. Ltd., ORG), (Accelink Technologies 002281, ORG), (Oct, DATE), (Asian Daily China Accelink Self, ORG), (OUTPERFORM Credit Suisse, ORG), (Asian Daily, ORG), (China Accelink, ORG), (Credit Suisse, ORG), (China Communication Infrastructure Sector Accelerating, ORG), (2H21, CARDINAL), (1H22, CARDINAL), (Credit Suisse, ORG), (China, GPE), (2H21 1H22, DATE)]","[0.008848447, 0.022734545, 0.004473734, 0.043637127, 0.014347288, -0.0021193868, 0.023623507, 0.015841195, -0.0026016978, -0.0033551822, 0.011579837, -0.013272229, 0.023791572, 0.019016426, 0.010336247, 0.016818805, 0.03360644, 0.031600226, -0.03508511, -0.04117013, 0.0033134096, -0.025514217, 0.0123653505, -0.002982897, -0.021458512, 0.006373497, -0.0016728467, 0.0077357045, -0.005352147, 0.008600678, 0.02673737, -0.0009961833, -0.019565567, -0.011589401, -0.02358849, 0.0086162565, -0.008671816, -0.0026517317, -0.006786868, 0.015814943, 0.023025855, -0.007868314, 0.004779275, -0.0005082672, 0.015922712, 0.0064148433, -0.024161678, -0.013623622, 0.0096126385, 0.022582088, 0.016089456, -0.025327073, -0.040536117, -0.03388891, -0.026370447, 0.01928711, 0.004058959, 0.016338598, -0.016164314, -0.009347723, -0.012014399, 0.0003396705, 0.013645574, -0.0020095538, -0.011325044, 0.013372282, -0.009793751, 0.02051155, 0.0010044501, -0.012288623, 0.008478044, -0.010930072, -0.012727488, 0.017534439, 0.019846035, 4.5679073e-05, 0.022356406, 0.022452267, -0.004057881, -0.004581789, -0.04011566, 0.00014127947, -0.014762493, 0.009078109, -0.0003841475, -0.01458169, 0.027583037, -0.011476619, 0.0035584206, -0.017452747, -0.023126615, -0.0034920475, 0.0010941738, 0.026937898, 0.022811465, -0.0055589285, 0.024788275, -0.019142825, -0.027007366, 0.017979683]"
3,002405.SZ,"[(ADAS Company MINIEYE Closes C Round of Financing, ORG), (270 Million RMB, MONEY), (ADAS, ORG), (MINIEYE, ORG), (World ADAS & AV Technologies and Components Market Report Focus on Camera Radar & Lidar, ORG), (Mapping & Localization and Robotaxis, ORG), (Montage Rare, PERSON), (Credit Suisse, ORG), (NavInfo Co. Ltd. Mergers & Acquisitions M&A Partnerships & Alliances and, ORG), (NavInfo Co. Ltd., ORG), (Mergers & Acquisitions, ORG), (China, GPE), (September, DATE), (Daiwa Capital Markets Hong Kong Ltd., ORG), (Technavio, ORG)]","[-0.012285153, 0.0051711756, -0.009488218, -0.011240473, -0.00029166605, 0.0015796106, 0.0047223736, 0.01273455, -0.018134397, -0.0031603675, -0.005708612, -0.0048993924, -0.009435215, -0.0034169569, -0.0009570962, -0.014597627, -0.00044089163, -0.0039693615, 0.0019607146, -0.014789568, -0.00096302765, -0.004248865, 0.015002046, 0.006484641, -0.0093979435, -0.0024531195, 0.0021205186, -0.008129901, -0.0074088466, 0.0051197098, 0.010011222, -0.0031575682, -0.0025034614, -0.015694594, 0.0025010144, 0.01019062, -0.0005902812, 0.002725234, 0.0034363936, -0.005861491, 0.013730442, -0.015864674, -0.013275149, 0.0057145017, 0.008461293, -0.004439114, -0.0058063446, 0.008285861, 0.0064041195, -0.0045302943, 0.005616415, -0.00480606, 0.016545719, 0.0007590757, -0.010777331, -0.00952492, 0.0055275965, -0.014114654, -0.0120908, -0.010216778, 0.008843435, -0.002672897, 0.008131674, -0.0032558911, 0.0011260735, 0.0024239144, 0.0045006634, 0.01720377, -0.014647702, 0.0027312592, -0.005858267, 0.013005161, 0.004942186, 0.0055130697, 0.0085399905, 0.014106293, -0.000514546, 0.0055610477, 0.005746005, -0.005150673, -0.0030401582, -0.014282067, -0.0031908748, -0.0099392645, -0.006999008, -0.017524285, 0.0040374734, 0.015518048, 0.0012443704, -0.00026018397, 0.012149032, 0.005407119, -0.0021779914, -0.00845386, 0.014995591, 0.00062859454, 0.004337622, -0.010816402, 0.0050162473, -0.010416337]"
4,002432.SZ,"[(Blood Glucose Monitoring Devices Market Size, ORG), (Arizton, ORG), (USD 37 Billion, MONEY), (Arizton, GPE), (MarketGrader Research Report, ORG), (Andon Health Co. Ltd., ORG)]","[-0.0053317393, 0.004776445, -0.001502753, 0.0034662753, 0.0035731315, -0.00087944994, 3.8750375e-05, -0.0031882979, 0.0019851956, 0.00016328227, 0.0013268233, -0.0045986963, 0.0030157785, 0.001078754, 0.002770341, 9.3760624e-05, -0.0006036127, -0.0023875474, 0.006140486, -0.00952849, 0.0072328723, 0.0036132087, 0.0038315852, 0.0012915616, -0.00271956, 0.0055497224, -0.00027923202, 0.0011575716, 0.0037904163, -0.005464594, -0.00079543993, 7.63339e-05, 0.0003364312, -0.0020087538, 0.0009987624, -0.00095463434, 0.0028246972, 0.00040393323, -0.0023721347, 0.00036553823, -0.0008022532, -0.006255254, -0.004025663, 0.0059383055, 0.0033141286, 0.0027991494, 0.0013822813, -0.0017208755, -0.00031059462, 0.0054165563, 0.00456171, 0.007749708, -0.004185197, -0.0027683633, 0.0046585617, -0.0015521832, -0.0008630006, -0.0014547571, -0.001629229, 0.00091511925, -0.0040355083, 0.0012087622, -0.00574177, -0.000574941, -0.00016824342, 0.0020376546, 0.0019674988, 0.004899121, -0.00058221916, 0.0045407894, -0.0027386995, 0.0010219576, 0.00041526742, 0.0026307073, 0.0026763498, 0.0022388392, -0.002012988, -0.00010173619, -0.0032651175, -0.00020397893, 0.0012266169, 0.0005489767, -0.0037788786, -0.0034887344, 0.0028559896, -0.0019692557, -0.00418318, -0.0017921457, -0.0039599915, -0.001791293, -0.00240478, -0.004270088, 0.0067307116, -0.004359066, 0.0035517435, 0.0008249106, -0.0022520884, 0.0018191576, 0.0053916764, 0.00089462864]"

In [20]:
import pandas as pd

# Step 1: Expand RIC_Vector into separate columns
ric_vector_df = grouped_df['RIC_Vector'].apply(lambda x: pd.Series(x))

# Step 2: Rename columns as word2vec_0, word2vec_1, ..., word2vec_99
ric_vector_df.columns = [f'word2vec_{i}' for i in range(ric_vector_df.shape[1])]

# Step 3: Concatenate back with RIC for clarity
final_word2vec_df = pd.concat([grouped_df[['RIC']], ric_vector_df], axis=1)

In [21]:
final_word2vec_df.head()

,RIC,word2vec_0,word2vec_1,word2vec_2,word2vec_3,word2vec_4,word2vec_5,word2vec_6,word2vec_7,word2vec_8,...,word2vec_90,word2vec_91,word2vec_92,word2vec_93,word2vec_94,word2vec_95,word2vec_96,word2vec_97,word2vec_98,word2vec_99
0,000150.KS,-0.002995,-0.001533,-0.003683,0.002817,-0.000889,-0.002560,-0.001589,0.006617,-0.003744,...,-0.001147,0.002694,0.002239,0.000286,0.004902,-0.005414,-0.001387,-0.001654,0.004220,-0.000098
1,002230.SZ,-0.001343,0.018510,-0.004366,0.006705,-0.009783,-0.002311,0.014847,0.019902,-0.010111,...,0.001610,0.013561,-0.011976,-0.019470,0.010248,-0.006920,0.018762,-0.011744,0.014970,-0.006215
2,002281.SZ,0.008848,0.022735,0.004474,0.043637,0.014347,-0.002119,0.023624,0.015841,-0.002602,...,-0.023127,-0.003492,0.001094,0.026938,0.022811,-0.005559,0.024788,-0.019143,-0.027007,0.017980
3,002405.SZ,-0.012285,0.005171,-0.009488,-0.011240,-0.000292,0.001580,0.004722,0.012735,-0.018134,...,0.012149,0.005407,-0.002178,-0.008454,0.014996,0.000629,0.004338,-0.010816,0.005016,-0.010416
4,002432.SZ,-0.005332,0.004776,-0.001503,0.003466,0.003573,-0.000879,0.000039,-0.003188,0.001985,...,-0.002405,-0.004270,0.006731,-0.004359,0.003552,0.000825,-0.002252,0.001819,0.005392,0.000895

# Combining vectors and numerical data

In [22]:
numerical = pd.read_excel("Numerical_Working.xlsx")

In [23]:
numerical.shape

(3882, 24)

In [24]:
# Drop unnamed columns if present
numerical = numerical.drop(columns=["Unnamed: 0.1", "Unnamed: 0"], errors="ignore")

In [25]:
# Merge numerical and GloVe vectors on RIC
merged = pd.merge(numerical, final_word2vec_df, how="inner", left_on="Instrument", right_on="RIC")

In [26]:
merged.shape

(2216, 123)

In [27]:
merged.head()

,Instrument,AD-30,AD,Gross Profit Margin - %,Net Income after Minority Interest,Total Capital,"Operating Margin - %, TTM",Free Cash Flow,Revenue from Business Activities - Total,Revenue from Business Activities - Total.1,...,word2vec_90,word2vec_91,word2vec_92,word2vec_93,word2vec_94,word2vec_95,word2vec_96,word2vec_97,word2vec_98,word2vec_99
0,COR,2021-10-16 00:00:00,2021-11-15,40.21891,79309000.0,1.788389e+09,22.855325,3427000.0,6.068240e+08,5.727270e+08,...,-0.000491,-0.000278,0.000211,0.000740,0.001753,0.000070,0.000940,-0.001314,-0.000523,0.000986
1,DVD,2021-10-10 00:00:00,2021-11-09,26.66113,7482000.0,6.902700e+07,25.492173,1195000.0,3.854300e+07,4.596300e+07,...,0.014182,0.000895,-0.002614,-0.004700,0.029920,-0.006453,0.013554,-0.017020,-0.002852,-0.006225
2,MCFE.O,2021-10-09 00:00:00,2021-11-08,62.31934,-118000000.0,2.187000e+09,10.883691,718000000.0,2.906000e+09,2.635000e+09,...,0.001688,0.006360,0.002993,0.002645,0.007534,0.001654,-0.009678,-0.007082,-0.004082,-0.000546
3,CPLG.K,2021-10-09 00:00:00,2021-11-08,-10.70560,-178000000.0,1.682000e+09,-30.140187,-62000000.0,4.110000e+08,8.120000e+08,...,0.009415,0.018594,0.001772,-0.015264,0.014594,-0.012339,-0.003088,-0.006606,0.025307,-0.014426
4,MNR,2021-10-06 00:00:00,2021-11-05,81.94939,-22143000.0,1.912112e+09,49.454326,-82396000.0,1.678170e+08,1.548210e+08,...,0.007005,0.000676,-0.005441,-0.001667,0.006630,-0.003131,-0.001349,-0.008771,0.005446,-0.004270

# Sentiment

In [28]:
sentiment = pd.read_excel("Sentiment.xlsx")

In [29]:
sentiment.head()

         RIC  Avg_Sentiment_Label
0  000150.KS             0.793103
1  002230.SZ             0.666667
2  002281.SZ             0.454545
3  002405.SZ             0.428571
4  002432.SZ             1.000000

In [30]:
merged = pd.merge(merged, sentiment, how="inner", left_on="Instrument", right_on="RIC")

In [31]:
merged.head()

,Instrument,AD-30,AD,Gross Profit Margin - %,Net Income after Minority Interest,Total Capital,"Operating Margin - %, TTM",Free Cash Flow,Revenue from Business Activities - Total,Revenue from Business Activities - Total.1,...,word2vec_92,word2vec_93,word2vec_94,word2vec_95,word2vec_96,word2vec_97,word2vec_98,word2vec_99,RIC_y,Avg_Sentiment_Label
0,COR,2021-10-16 00:00:00,2021-11-15,40.21891,79309000.0,1.788389e+09,22.855325,3427000.0,6.068240e+08,5.727270e+08,...,0.000211,0.000740,0.001753,0.000070,0.000940,-0.001314,-0.000523,0.000986,COR,0.503566
1,DVD,2021-10-10 00:00:00,2021-11-09,26.66113,7482000.0,6.902700e+07,25.492173,1195000.0,3.854300e+07,4.596300e+07,...,-0.002614,-0.004700,0.029920,-0.006453,0.013554,-0.017020,-0.002852,-0.006225,DVD,0.809524
2,MCFE.O,2021-10-09 00:00:00,2021-11-08,62.31934,-118000000.0,2.187000e+09,10.883691,718000000.0,2.906000e+09,2.635000e+09,...,0.002993,0.002645,0.007534,0.001654,-0.009678,-0.007082,-0.004082,-0.000546,MCFE.O,0.781818
3,CPLG.K,2021-10-09 00:00:00,2021-11-08,-10.70560,-178000000.0,1.682000e+09,-30.140187,-62000000.0,4.110000e+08,8.120000e+08,...,0.001772,-0.015264,0.014594,-0.012339,-0.003088,-0.006606,0.025307,-0.014426,CPLG.K,0.666667
4,MNR,2021-10-06 00:00:00,2021-11-05,81.94939,-22143000.0,1.912112e+09,49.454326,-82396000.0,1.678170e+08,1.548210e+08,...,-0.005441,-0.001667,0.006630,-0.003131,-0.001349,-0.008771,0.005446,-0.004270,MNR,1.000000

# Feature Selection with RFE

In [32]:
# Step 1: Drop target and unnecessary columns
X = merged.drop(columns=["Instrument", "AD", "AD-30", "Label"])
y = merged["Label"]

# Step 2: Keep only numerical columns
X = X.select_dtypes(include=['number'])  # Keep only int/float columns

# Step 3: Scaling (optional for Random Forest but good for consistency)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 4: Feature selection with RFE
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE

model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight="balanced")
rfe = RFE(estimator=model, n_features_to_select=50, step=10, verbose=1)
X_selected = rfe.fit_transform(X_scaled, y)

# Step 5: Get feature names
selected_features = X.columns[rfe.get_support()]
X_selected_df = pd.DataFrame(X_selected, columns=selected_features)

Fitting estimator with 119 features.
Fitting estimator with 109 features.
Fitting estimator with 99 features.
Fitting estimator with 89 features.
Fitting estimator with 79 features.
Fitting estimator with 69 features.
Fitting estimator with 59 features.

In [36]:
X_selected_df.shape

(2216, 50)

In [33]:
X_selected_df.head()

,Gross Profit Margin - %,Net Income after Minority Interest,Total Capital,Free Cash Flow,Revenue from Business Activities - Total,Revenue from Business Activities - Total.1,Revenue from Business Activities - Total.2,Revenue from Business Activities - Total.3,Current Ratio,Price To Book Value Per Share (Daily Time Series Ratio),...,word2vec_61,word2vec_71,word2vec_78,word2vec_81,word2vec_86,word2vec_88,word2vec_92,word2vec_94,word2vec_99,Avg_Sentiment_Label
0,-0.011713,-0.028612,-0.038890,-0.016175,-0.046135,-0.044215,-0.044582,-0.047133,-0.399799,0.275817,...,0.235085,-0.061244,0.158181,0.102279,-0.678453,-0.300352,0.015876,-0.876598,-0.242376,-0.001212
1,-0.313778,-0.028733,-0.039166,-0.016180,-0.046332,-0.044386,-0.044758,-0.047344,0.212090,0.022465,...,-0.485344,0.916858,0.935876,-0.855071,0.330537,-0.717210,-0.317035,1.171323,-0.760501,0.891525
2,0.480681,-0.028944,-0.038826,-0.014838,-0.045340,-0.043544,-0.043923,-0.046360,-0.401813,0.020841,...,0.656171,0.531424,0.115371,-0.477624,-1.325744,-0.535916,0.343792,-0.456287,-0.352434,0.810685
3,-1.146303,-0.029045,-0.038907,-0.016298,-0.046203,-0.044137,-0.044470,-0.046961,0.432580,0.022458,...,1.187239,1.033560,1.208084,-1.226435,-1.954682,-1.301515,0.199861,0.056993,-1.349756,0.474690
4,0.918035,-0.028783,-0.038870,-0.016336,-0.046287,-0.044351,-0.044726,-0.047311,1.807264,0.022920,...,0.440908,0.462585,0.527929,-0.453128,-0.685875,-0.107520,-0.650180,-0.522044,-0.619982,1.447306

In [38]:
y.to_excel("final_y.xlsx", index=False)

In [37]:
X_selected_df.to_excel("final_df.xlsx", index=False)

In [34]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xgboost in ./.local/lib/python3.12/site-packages (3.0.0)
Requirement already satisfied: numpy in ./.local/lib/python3.12/site-packages (from xgboost) (1.26.4)
Requirement already satisfied: nvidia-nccl-cu12 in ./.local/lib/python3.12/site-packages (from xgboost) (2.26.2)
Requirement already satisfied: scipy in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from xgboost) (1.13.1)

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE
import numpy as np

ModuleNotFoundError: No module named 'imblearn'